"""Base data models and metadata primitives for GroundTruth."""

from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Dict, List, Optional


class MetaLevel(str, Enum):
    """OMG MOF 2.5.1 Meta-Modeling Architecture Levels."""
    M3_META_METAMODEL = "M3"   # OMG MOF 2.5.1 foundation
    M2_METAMODEL = "M2"        # GroundTruth DAMA-aligned data modeling grammar
    M1_DOMAIN_MODEL = "M1"     # Particular domain data model (e.g. Sales, Payments)
    M0_INSTANCE_DATA = "M0"    # Runtime rows and instances


class AuthorityTier(str, Enum):
    """Semantic confidence and governance tier."""
    DECLARED = "DECLARED"  # Authoritative human or lead architect specification
    DERIVED = "DERIVED"    # Deterministically generated by a transform or projection
    INFERRED = "INFERRED"  # Discovered or synthesized by an autonomous AI agent


class LifecycleState(str, Enum):
    """Lifecycle status of a data element."""
    DRAFT = "DRAFT"
    ACTIVE = "ACTIVE"
    DEPRECATED = "DEPRECATED"
    RETIRED = "RETIRED"


@dataclass
class DataProvenance:
    """Provenance tracking for data models and projections."""
    meta_level: MetaLevel = MetaLevel.M1_DOMAIN_MODEL
    authority: AuthorityTier = AuthorityTier.DECLARED
    confidence: float = 1.0
    created_at: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    governing_definition: str = "decision://arch/adr-0001-require-mof-conformance-for-the-governing-model-definition"
    author: Optional[str] = None

    def to_dict(self) -> Dict[str, Any]:
        return {
            "meta_level": self.meta_level.value,
            "authority": self.authority.value,
            "confidence": self.confidence,
            "created_at": self.created_at,
            "governing_definition": self.governing_definition,
            "author": self.author,
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "DataProvenance":
        return cls(
            meta_level=MetaLevel(data.get("meta_level", "M1")),
            authority=AuthorityTier(data.get("authority", "DECLARED")),
            confidence=float(data.get("confidence", 1.0)),
            created_at=data.get("created_at", datetime.now(timezone.utc).isoformat()),
            governing_definition=data.get("governing_definition", "decision://arch/adr-0001-require-mof-conformance-for-the-governing-model-definition"),
            author=data.get("author"),
        )
